# Generated by Django 5.0.6 on 2024-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_remove_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(through='mercado.ItemPedido', to='mercado.produto'),
        ),
    ]
